workspace:
  base: /go
  path: src/github.com/umputun/rlb-stats

pipeline:
  docker:
    image: plugins/docker
    repo: umputun/rlb-stats
    secrets: [ docker_username, docker_password ]
    tags:
    - ${DRONE_REPO_BRANCH}
    - latest