version: '2'
services:

  rlb-stats:
    build: .
    image: umputun/rlb-stats:latest
    hostname: rlb-stats
    container_name: rlb-stats

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
    - /tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock

    ports:
    - "8080:8080"
