version: '2'
services:

  rlb-stats:
    build: .
    image: umputun/rlb-stats:latest
    hostname: rlb-stats
    container_name: rlb-stats

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
    - /tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock

    ports:
    - "80:80"

    # useful for test purposes if you don't have user 1001 owning /var/run/docker.sock
#    user: root
    # these regexp and and container_name allow to watch for it's own logs and show information from them
    # which is useful for test purposes
#    environment:
#    - REGEXP=^(?P<Date>.+) "GET https?://(?P<DestinationNode>.+?)(?P<FileName>/[^?]+)(?:\?.*) HTTP/1.1" from (?P<SourceIP>.+):\d+ - (?:.+) in (?P<AnswerTime>.+)$$
#    - CONTAINER_NAME=rlb-stats
#    - LOG_TAIL=all
